
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Nov 15 19:19:24 EST 2013
//----------------------------------------------------

package rddl.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BOOL = 83;
  public static final int TIMES = 51;
  public static final int DISCRETE = 45;
  public static final int NORMAL = 46;
  public static final int REAL = 86;
  public static final int LCURLY = 12;
  public static final int MULTIVALUED = 14;
  public static final int CONTINUOUS = 10;
  public static final int SEMI = 59;
  public static final int GREATEREQ = 69;
  public static final int EQUIV = 71;
  public static final int ENUM = 84;
  public static final int PROD_OVER = 34;
  public static final int RBRACK = 65;
  public static final int NON_FLUENTS = 25;
  public static final int COMMA = 62;
  public static final int LEVEL = 30;
  public static final int RPAREN = 61;
  public static final int LBRACK = 63;
  public static final int PVARIABLES = 22;
  public static final int EXPONENTIAL = 48;
  public static final int INTEGER = 78;
  public static final int DOUBLE = 79;
  public static final int ACTION = 29;
  public static final int LPAREN = 60;
  public static final int FALSE = 75;
  public static final int NOT = 40;
  public static final int STATE_ACTION_CONSTRAINTS = 16;
  public static final int OBJECT = 82;
  public static final int INSTANCE = 3;
  public static final int VAR = 81;
  public static final int THEN = 56;
  public static final int REWARD = 35;
  public static final int INTERMEDIATE_NODES = 15;
  public static final int DISCOUNT = 5;
  public static final int NON_FLUENT = 87;
  public static final int TYPES = 18;
  public static final int OBSERVATION = 28;
  public static final int MOD = 52;
  public static final int INTERMEDIATE = 27;
  public static final int COMP_EQUAL = 73;
  public static final int SUM_OVER = 33;
  public static final int CPFS = 88;
  public static final int TRUE = 74;
  public static final int PLUS = 50;
  public static final int FORALL = 36;
  public static final int EXISTS = 37;
  public static final int REQUIREMENTS = 8;
  public static final int DOMAIN = 2;
  public static final int STATE = 23;
  public static final int KRON_DELTA = 41;
  public static final int SWITCH = 58;
  public static final int POS_INF = 20;
  public static final int GREATER = 68;
  public static final int DIV = 53;
  public static final int ELSE = 57;
  public static final int POISSON = 47;
  public static final int INT = 85;
  public static final int CONCURRENT = 9;
  public static final int NEG_INF = 19;
  public static final int INIT_STATE = 7;
  public static final int EOF = 0;
  public static final int DEFAULT = 24;
  public static final int DIRAC_DELTA = 42;
  public static final int UNDERSCORE = 17;
  public static final int MINUS = 54;
  public static final int MIN_NONDEF_INSTANCE = 31;
  public static final int OR = 39;
  public static final int IDENT = 80;
  public static final int error = 1;
  public static final int LESSEQ = 67;
  public static final int IF = 55;
  public static final int CDFS = 89;
  public static final int COLON = 64;
  public static final int MAX_NONDEF_ACTIONS = 21;
  public static final int INTEGER_VALUED = 11;
  public static final int UNIFORM = 43;
  public static final int ENUM_VAL = 90;
  public static final int CASE = 26;
  public static final int GEOMETRIC = 49;
  public static final int BERNOULLI = 44;
  public static final int OBJECTS = 6;
  public static final int LESS = 66;
  public static final int NEQ = 76;
  public static final int HORIZON = 4;
  public static final int IMPLY = 70;
  public static final int AND = 38;
  public static final int MAX_NONDEF_INSTANCE = 32;
  public static final int UMINUS = 77;
  public static final int ASSIGN_EQUAL = 72;
  public static final int RCURLY = 13;
}

