
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Dec 10 16:52:53 EST 2013
//----------------------------------------------------

package rddl.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BOOL = 75;
  public static final int TIMES = 44;
  public static final int DISCRETE = 38;
  public static final int NORMAL = 39;
  public static final int REAL = 77;
  public static final int LCURLY = 9;
  public static final int SEMI = 51;
  public static final int GREATEREQ = 61;
  public static final int EQUIV = 63;
  public static final int PROD_OVER = 27;
  public static final int RBRACK = 57;
  public static final int NON_FLUENTS = 20;
  public static final int COMMA = 54;
  public static final int LEVEL = 25;
  public static final int RPAREN = 53;
  public static final int LBRACK = 55;
  public static final int PVARIABLES = 17;
  public static final int EXPONENTIAL = 41;
  public static final int INTEGER = 70;
  public static final int DOUBLE = 71;
  public static final int ACTION = 24;
  public static final int LPAREN = 52;
  public static final int FALSE = 67;
  public static final int NOT = 33;
  public static final int STATE_ACTION_CONSTRAINTS = 11;
  public static final int OBJECT = 74;
  public static final int INSTANCE = 3;
  public static final int VAR = 73;
  public static final int THEN = 48;
  public static final int REWARD = 28;
  public static final int DISCOUNT = 5;
  public static final int NON_FLUENT = 78;
  public static final int TYPES = 13;
  public static final int OBSERVATION = 23;
  public static final int INTERMEDIATE = 22;
  public static final int COMP_EQUAL = 65;
  public static final int SUM_OVER = 26;
  public static final int CPFS = 79;
  public static final int TRUE = 66;
  public static final int PLUS = 43;
  public static final int FORALL = 29;
  public static final int EXISTS = 30;
  public static final int REQUIREMENTS = 8;
  public static final int DOMAIN = 2;
  public static final int STATE = 18;
  public static final int KRON_DELTA = 34;
  public static final int SWITCH = 50;
  public static final int POS_INF = 15;
  public static final int GREATER = 60;
  public static final int DIV = 45;
  public static final int ELSE = 49;
  public static final int POISSON = 40;
  public static final int INT = 76;
  public static final int NEG_INF = 14;
  public static final int INIT_STATE = 7;
  public static final int EOF = 0;
  public static final int DEFAULT = 19;
  public static final int DIRAC_DELTA = 35;
  public static final int UNDERSCORE = 12;
  public static final int MINUS = 46;
  public static final int OR = 32;
  public static final int IDENT = 72;
  public static final int error = 1;
  public static final int LESSEQ = 59;
  public static final int IF = 47;
  public static final int CDFS = 80;
  public static final int COLON = 56;
  public static final int MAX_NONDEF_ACTIONS = 16;
  public static final int UNIFORM = 36;
  public static final int ENUM_VAL = 81;
  public static final int CASE = 21;
  public static final int GEOMETRIC = 42;
  public static final int BERNOULLI = 37;
  public static final int OBJECTS = 6;
  public static final int LESS = 58;
  public static final int NEQ = 68;
  public static final int HORIZON = 4;
  public static final int IMPLY = 62;
  public static final int AND = 31;
  public static final int UMINUS = 69;
  public static final int ASSIGN_EQUAL = 64;
  public static final int RCURLY = 10;
}

