
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Oct 27 06:57:46 EST 2010
//----------------------------------------------------

package rddl.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int HIGHEST = 88;
  public static final int BOOL = 95;
  public static final int TIMES = 58;
  public static final int DISCRETE = 52;
  public static final int NORMAL = 53;
  public static final int REAL = 98;
  public static final int LCURLY = 13;
  public static final int TYPE = 27;
  public static final int MULTIVALUED = 15;
  public static final int CONTINUOUS = 11;
  public static final int SEMI = 65;
  public static final int GREATEREQ = 78;
  public static final int EQUIV = 81;
  public static final int ENUM = 96;
  public static final int RBRACK = 74;
  public static final int PROD_OVER = 40;
  public static final int NON_FLUENTS = 30;
  public static final int COMMA = 70;
  public static final int LEVEL = 36;
  public static final int DEFINE = 2;
  public static final int RPAREN = 68;
  public static final int LBRACK = 71;
  public static final int PARAM_TYPES = 25;
  public static final int PVARIABLES = 26;
  public static final int EXPONENTIAL = 55;
  public static final int INTEGER = 90;
  public static final int DOUBLE = 91;
  public static final int ACTION = 34;
  public static final int LPAREN = 67;
  public static final int FALSE = 86;
  public static final int NOT = 47;
  public static final int STATE_ACTION_CONSTRAINTS = 17;
  public static final int OBJECT = 94;
  public static final int INSTANCE = 4;
  public static final int VAR = 93;
  public static final int THEN = 62;
  public static final int REWARD = 42;
  public static final int INTERMEDIATE_NODES = 16;
  public static final int DISCOUNT = 6;
  public static final int NON_FLUENT = 99;
  public static final int TYPES = 19;
  public static final int OBSERVATION = 33;
  public static final int PARAMS = 41;
  public static final int MOD = 84;
  public static final int INTERMEDIATE = 32;
  public static final int COMP_EQUAL = 83;
  public static final int SUM_OVER = 39;
  public static final int CPFS = 100;
  public static final int TRUE = 85;
  public static final int PLUS = 57;
  public static final int FORALL = 43;
  public static final int EXISTS = 44;
  public static final int REQUIREMENTS = 9;
  public static final int DOMAIN = 3;
  public static final int STATE = 28;
  public static final int KRON_DELTA = 48;
  public static final int QST = 72;
  public static final int SWITCH = 64;
  public static final int POS_INF = 21;
  public static final int GREATER = 77;
  public static final int DIV = 59;
  public static final int ELSE = 63;
  public static final int POISSON = 54;
  public static final int DOT = 69;
  public static final int INT = 97;
  public static final int CONCURRENT = 10;
  public static final int NEG_INF = 20;
  public static final int CONSTANTS = 22;
  public static final int INIT_STATE = 8;
  public static final int EOF = 0;
  public static final int BANG = 66;
  public static final int DEFAULT = 29;
  public static final int COUNT = 79;
  public static final int DIRAC_DELTA = 49;
  public static final int UNDERSCORE = 18;
  public static final int RELATIONS = 23;
  public static final int MINUS = 60;
  public static final int MIN_NONDEF_INSTANCE = 37;
  public static final int OR = 46;
  public static final int IDENT = 92;
  public static final int error = 1;
  public static final int LESSEQ = 76;
  public static final int IF = 61;
  public static final int CDFS = 101;
  public static final int COLON = 73;
  public static final int MAX_NONDEF_ACTIONS = 24;
  public static final int INTEGER_VALUED = 12;
  public static final int UNIFORM = 50;
  public static final int ENUM_VAL = 102;
  public static final int CASE = 31;
  public static final int GEOMETRIC = 56;
  public static final int BERNOULLI = 51;
  public static final int RANGE = 35;
  public static final int OBJECTS = 7;
  public static final int LESS = 75;
  public static final int NEQ = 87;
  public static final int HORIZON = 5;
  public static final int IMPLY = 80;
  public static final int AND = 45;
  public static final int MAX_NONDEF_INSTANCE = 38;
  public static final int UMINUS = 89;
  public static final int ASSIGN_EQUAL = 82;
  public static final int RCURLY = 14;
}

