
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 16 15:44:04 CET 2018
//----------------------------------------------------

package rddl.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ACTION_PRECONDITIONS = 14;
  public static final int BOOL = 87;
  public static final int TIMES = 47;
  public static final int DISCRETE = 42;
  public static final int NORMAL = 43;
  public static final int REAL = 89;
  public static final int LCURLY = 9;
  public static final int GAMMA = 58;
  public static final int SEMI = 62;
  public static final int GREATEREQ = 73;
  public static final int EQUIV = 75;
  public static final int DERIVED_FLUENT = 11;
  public static final int RBRACK = 69;
  public static final int NON_FLUENTS = 22;
  public static final int COMMA = 65;
  public static final int LEVEL = 27;
  public static final int MULTINOMIAL = 59;
  public static final int RPAREN = 64;
  public static final int LBRACK = 66;
  public static final int PVARIABLES = 20;
  public static final int EXPONENTIAL = 45;
  public static final int INTEGER = 82;
  public static final int DOUBLE = 83;
  public static final int ACTION = 26;
  public static final int LPAREN = 63;
  public static final int STATE_INVARIANTS = 15;
  public static final int FALSE = 79;
  public static final int NOT = 37;
  public static final int STATE_ACTION_CONSTRAINTS = 13;
  public static final int OBJECT = 86;
  public static final int INSTANCE = 3;
  public static final int VAR = 85;
  public static final int THEN = 51;
  public static final int REWARD = 30;
  public static final int DISCOUNT = 5;
  public static final int NON_FLUENT = 90;
  public static final int TYPES = 16;
  public static final int OBSERVATION = 25;
  public static final int INTERMEDIATE = 24;
  public static final int COMP_EQUAL = 77;
  public static final int CPFS = 91;
  public static final int TERMINATE_WHEN = 52;
  public static final int TRUE = 78;
  public static final int PLUS = 46;
  public static final int FORALL = 31;
  public static final int QUESTION = 68;
  public static final int EXISTS = 33;
  public static final int REQUIREMENTS = 8;
  public static final int DOMAIN = 2;
  public static final int STATE = 21;
  public static final int KRON_DELTA = 38;
  public static final int SWITCH = 54;
  public static final int POS_INF = 18;
  public static final int GREATER = 72;
  public static final int DIV = 48;
  public static final int ELSE = 53;
  public static final int POISSON = 44;
  public static final int DOT = 55;
  public static final int AMPERSAND = 35;
  public static final int INT = 88;
  public static final int NEG_INF = 17;
  public static final int INIT_STATE = 7;
  public static final int EOF = 0;
  public static final int DEFAULT = 28;
  public static final int DIRAC_DELTA = 39;
  public static final int UNDERSCORE = 12;
  public static final int MINUS = 49;
  public static final int TERMINAL = 61;
  public static final int AGG_OPER = 29;
  public static final int OR = 36;
  public static final int IDENT = 84;
  public static final int error = 1;
  public static final int LESSEQ = 71;
  public static final int IF = 50;
  public static final int CDFS = 92;
  public static final int COLON = 67;
  public static final int OTHERWISE = 56;
  public static final int MAX_NONDEF_ACTIONS = 19;
  public static final int UNIFORM = 40;
  public static final int ENUM_VAL = 93;
  public static final int WEIBULL = 57;
  public static final int CASE = 23;
  public static final int BERNOULLI = 41;
  public static final int OBJECTS = 6;
  public static final int LESS = 70;
  public static final int NEQ = 80;
  public static final int HORIZON = 4;
  public static final int IMPLY = 74;
  public static final int AND = 34;
  public static final int UMINUS = 81;
  public static final int ASSIGN_EQUAL = 76;
  public static final int DOLLAR_SIGN = 32;
  public static final int RCURLY = 10;
  public static final int DIRICHLET = 60;
}

