
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 13 23:01:32 EST 2014
//----------------------------------------------------

package rddl.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ACTION_PRECONDITIONS = 14;
  public static final int BOOL = 89;
  public static final int TIMES = 50;
  public static final int DISCRETE = 45;
  public static final int NORMAL = 46;
  public static final int REAL = 91;
  public static final int LCURLY = 9;
  public static final int GAMMA = 61;
  public static final int SEMI = 64;
  public static final int GREATEREQ = 75;
  public static final int EQUIV = 77;
  public static final int DERIVED_FLUENT = 11;
  public static final int RBRACK = 71;
  public static final int PROD_OVER = 30;
  public static final int NON_FLUENTS = 22;
  public static final int COMMA = 67;
  public static final int LEVEL = 27;
  public static final int MULTINOMIAL = 62;
  public static final int RPAREN = 66;
  public static final int LBRACK = 68;
  public static final int PVARIABLES = 20;
  public static final int EXPONENTIAL = 48;
  public static final int INTEGER = 84;
  public static final int DOUBLE = 85;
  public static final int ACTION = 26;
  public static final int LPAREN = 65;
  public static final int STATE_INVARIANTS = 15;
  public static final int FALSE = 81;
  public static final int NOT = 40;
  public static final int STATE_ACTION_CONSTRAINTS = 13;
  public static final int OBJECT = 88;
  public static final int INSTANCE = 3;
  public static final int VAR = 87;
  public static final int THEN = 54;
  public static final int REWARD = 33;
  public static final int DISCOUNT = 5;
  public static final int NON_FLUENT = 92;
  public static final int TYPES = 16;
  public static final int OBSERVATION = 25;
  public static final int INTERMEDIATE = 24;
  public static final int COMP_EQUAL = 79;
  public static final int SUM_OVER = 29;
  public static final int CPFS = 93;
  public static final int TERMINATE_WHEN = 55;
  public static final int TRUE = 80;
  public static final int PLUS = 49;
  public static final int FORALL = 34;
  public static final int QUESTION = 70;
  public static final int EXISTS = 36;
  public static final int REQUIREMENTS = 8;
  public static final int DOMAIN = 2;
  public static final int STATE = 21;
  public static final int KRON_DELTA = 41;
  public static final int SWITCH = 57;
  public static final int POS_INF = 18;
  public static final int GREATER = 74;
  public static final int DIV = 51;
  public static final int ELSE = 56;
  public static final int POISSON = 47;
  public static final int DOT = 58;
  public static final int AMPERSAND = 38;
  public static final int INT = 90;
  public static final int NEG_INF = 17;
  public static final int INIT_STATE = 7;
  public static final int EOF = 0;
  public static final int DEFAULT = 28;
  public static final int DIRAC_DELTA = 42;
  public static final int UNDERSCORE = 12;
  public static final int MINUS = 52;
  public static final int OR = 39;
  public static final int IDENT = 86;
  public static final int error = 1;
  public static final int LESSEQ = 73;
  public static final int IF = 53;
  public static final int CDFS = 94;
  public static final int COLON = 69;
  public static final int OTHERWISE = 59;
  public static final int MAX_NONDEF_ACTIONS = 19;
  public static final int UNIFORM = 43;
  public static final int ENUM_VAL = 95;
  public static final int WEIBULL = 60;
  public static final int CASE = 23;
  public static final int BERNOULLI = 44;
  public static final int OBJECTS = 6;
  public static final int LESS = 72;
  public static final int MAX_OVER = 32;
  public static final int NEQ = 82;
  public static final int HORIZON = 4;
  public static final int IMPLY = 76;
  public static final int AND = 37;
  public static final int UMINUS = 83;
  public static final int MIN_OVER = 31;
  public static final int ASSIGN_EQUAL = 78;
  public static final int DOLLAR_SIGN = 35;
  public static final int RCURLY = 10;
  public static final int DIRICHLET = 63;
}

